version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development

# não usei volumes pois utilizei o sqlite, e os dados do sqlite ficam salvos em arquivo.
# e o arquivo é criado e armazenado pelo volume configurado no compose.
# Por falta de tempo eu não utilizei um banco de dados como o postgres
#volumes:
#  database_data:

